### Unsupervised Learning

# Movie Recommender System

In [1]:
import pandas as pd
import numpy as np

In [2]:
credits = pd.read_csv("tmdb_5000_credits.csv")
movies = pd.read_csv("tmdb_5000_movies.csv")

In [3]:
print("Shape of Movies is:",movies.shape)
print("Shape of Credits is:",credits.shape)

Shape of Movies is: (4803, 20)
Shape of Credits is: (4803, 4)

In [4]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [5]:
credits.head(5)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [7]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [8]:
credits.isnull().sum()

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [9]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

### Merging Dataframes

In [10]:
#Merge on common field "title"
#name this as df
df = movies.merge(credits,on="title")

In [11]:
df.shape

(4809, 23)

In [12]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [13]:
df = df[['movie_id','title','overview','genres','keywords','cast','crew']]

In [14]:
df.columns

Index(['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew'], dtype='object')

In [15]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [17]:
#drop if any null values are presnt/some information is missing
df = df.dropna()

In [18]:
df.shape

(4806, 7)

In [19]:
df['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [20]:
df['genres'][0][2:6]

'"id"'

In [21]:
import ast
#Helper function used to etract names from fields.
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [22]:
df['genres'] = df['genres'].apply(convert)
df['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [23]:
df['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [24]:
df["keywords"] = df["keywords"].apply(convert)
df["keywords"]

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [25]:
df

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [26]:
df["cast"] = df["cast"].apply(convert)
df["cast"]

0       [Sam Worthington, Zoe Saldana, Sigourney Weave...
1       [Johnny Depp, Orlando Bloom, Keira Knightley, ...
2       [Daniel Craig, Christoph Waltz, Léa Seydoux, R...
3       [Christian Bale, Michael Caine, Gary Oldman, A...
4       [Taylor Kitsch, Lynn Collins, Samantha Morton,...
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805    [Edward Burns, Kerry Bishé, Marsha Dietlein, C...
4806    [Eric Mabius, Kristin Booth, Crystal Lowe, Geo...
4807    [Daniel Henney, Eliza Coupe, Bill Paxton, Alan...
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldm...
Name: cast, Length: 4806, dtype: object

In [27]:
df["cast"][0]

['Sam Worthington',
 'Zoe Saldana',
 'Sigourney Weaver',
 'Stephen Lang',
 'Michelle Rodriguez',
 'Giovanni Ribisi',
 'Joel David Moore',
 'CCH Pounder',
 'Wes Studi',
 'Laz Alonso',
 'Dileep Rao',
 'Matt Gerald',
 'Sean Anthony Moran',
 'Jason Whyte',
 'Scott Lawrence',
 'Kelly Kilgour',
 'James Patrick Pitt',
 'Sean Patrick Murphy',
 'Peter Dillon',
 'Kevin Dorman',
 'Kelson Henderson',
 'David Van Horn',
 'Jacob Tomuri',
 'Michael Blain-Rozgay',
 'Jon Curry',
 'Luke Hawker',
 'Woody Schultz',
 'Peter Mensah',
 'Sonia Yee',
 'Jahnel Curfman',
 'Ilram Choi',
 'Kyla Warren',
 'Lisa Roumain',
 'Debra Wilson',
 'Chris Mala',
 'Taylor Kibby',
 'Jodie Landau',
 'Julie Lamm',
 'Cullen B. Madden',
 'Joseph Brady Madden',
 'Frankie Torres',
 'Austin Wilson',
 'Sara Wilson',
 'Tamica Washington-Miller',
 'Lucy Briant',
 'Nathan Meister',
 'Gerry Blair',
 'Matthew Chamberlain',
 'Paul Yates',
 'Wray Wilson',
 'James Gaylyn',
 'Melvin Leno Clark III',
 'Carvon Futrell',
 'Brandon Jelkes',
 'Micah Moch',
 'Hanniyah Muhammad',
 'Christopher Nolen',
 'Christa Oliver',
 'April Marie Thomas',
 'Bravita A. Threatt',
 'Colin Bleasdale',
 'Mike Bodnar',
 'Matt Clayton',
 'Nicole Dionne',
 'Jamie Harrison',
 'Allan Henry',
 'Anthony Ingruber',
 'Ashley Jeffery',
 'Dean Knowsley',
 'Joseph Mika-Hunt',
 'Terry Notary',
 'Kai Pantano',
 'Logan Pithyou',
 'Stuart Pollock',
 'Raja',
 'Gareth Ruck',
 'Rhian Sheehan',
 'T. J. Storm',
 'Jodie Taylor',
 'Alicia Vela-Bailey',
 'Richard Whiteside',
 'Nikie Zambo',
 'Julene Renee']

In [28]:
len(df["cast"][0])

83

In [29]:
#Fetch only first 5 names from cast
df["cast"] = df["cast"].apply(lambda x: x[0:5])

In [30]:
df["cast"][0]

['Sam Worthington',
 'Zoe Saldana',
 'Sigourney Weaver',
 'Stephen Lang',
 'Michelle Rodriguez']

In [31]:
df["crew"][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [32]:
len(df["crew"][0])

22831

In [33]:
df["crew"][0][1:10]

'{"credit_'

In [34]:
df["crew"][0][1:20]

'{"credit_id": "52fe'

In [35]:
#Helper function to fetch Director name from field "crew".
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [36]:
df['crew'] = df['crew'].apply(fetch_director)

In [37]:
df['crew'][0]

['James Cameron']

In [38]:
df.sample(10)

,movie_id,title,overview,genres,keywords,cast,crew
1793,5902,A Bridge Too Far,Tells the story of operation Market Garden. A ...,"[Drama, History, War]","[netherlands, world war ii, panzer, british so...","[Dirk Bogarde, James Caan, Michael Caine, Sean...",[Richard Attenborough]
814,9327,The Nutty Professor,"Eddie Murphy stars as shy Dr. Sherman Klump, a...","[Fantasy, Comedy, Romance, Science Fiction]","[overweight, overweight man, duringcreditsstin...","[Eddie Murphy, Jada Pinkett Smith, James Cobur...",[Tom Shadyac]
1866,2140,Kiss of the Dragon,"Liu Jian, an elite Chinese police officer, com...","[Action, Crime, Thriller]","[paris, prostitute, drug]","[Jet Li, Bridget Fonda, Tchéky Karyo, Max Ryan...",[Chris Nahon]
2664,40880,Pandaemonium,"Set in England during the early 19th century, ...","[Drama, Foreign]",[],"[Linus Roache, John Hannah, Samantha Morton, E...",[Julien Temple]
2034,235260,Son of God,The life story of Jesus is told from his humbl...,[Drama],"[biography, resurrection]","[Roma Downey, Diogo Morgado, Louise Delamere, ...",[Christopher Spencer]
4771,228550,Raymond Did It,Mentally challenged Raymond Rourke gets blamed...,[Horror],"[high school, murder, slasher, teenager]","[Kyle Hoskins, Elissa Dowling, Linda Cieslik, ...",[Travis Legge]
432,8656,Deep Impact,A seven-mile-wide space rock is hurtling towar...,"[Action, Drama, Romance]","[usa president, nasa, metereologist, space mis...","[Robert Duvall, Téa Leoni, Elijah Wood, Vaness...",[Mimi Leder]
3715,17139,Character,J.W. Katadreuffe is the son of Joba Katadreuff...,"[Drama, Foreign, History]",[law and ethics],"[Jan Decleir, Fedja van Huêt, Betty Schuurman,...",[Mike van Diem]
4636,84188,Compliance,Sandra is the manager at a fast-food restauran...,"[Drama, Thriller, Crime]",[],"[Ann Dowd, Dreama Walker, Pat Healy, Philip Et...",[Craig Zobel]
3149,208869,Plastic,Sam &amp; Fordy run a credit card fraud scheme...,"[Drama, Action, Comedy, Crime]",[],"[Ed Speleers, Will Poulter, Alfie Allen, Sebas...",[Julian Gilbey]

In [39]:
#Helper function to remove spaces in between any names or entities so that it wont split during tokenization of words
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [40]:
df['cast'] = df['cast'].apply(collapse)
df['crew'] = df['crew'].apply(collapse)
df['genres'] = df['genres'].apply(collapse)
df['keywords'] = df['keywords'].apply(collapse)

In [41]:
df

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt,...",[RobertRodriguez]
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[EdwardBurns, KerryBishé, MarshaDietlein, Cait...",[EdwardBurns]
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe, GeoffG...",[ScottSmith]
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[DanielHenney, ElizaCoupe, BillPaxton, AlanRuc...",[DanielHsia]
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman,...","[BrianHerzlinger, JonGunn, BrettWinn]"

In [42]:
df["overview"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [43]:
text ="this is my pet, meet him "
text.split()

['this', 'is', 'my', 'pet,', 'meet', 'him']

In [44]:
df["overview"] = df["overview"].apply(lambda x: x.split())

In [45]:
df["overview"][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

In [46]:
df['tags'] = df['overview'] + df['genres'] + df['keywords'] + df['cast'] + df['crew']

In [47]:
df['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'StephenLang',
 'MichelleRodriguez',
 'JamesCameron']

In [48]:
#Creating new datframe by dropping overview,genres,keyword,cast & crew --> as we have combined all these entities and formed a new field named tags
new_df = df.drop(['overview','genres','keywords','cast','crew'],axis=1)

In [49]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [50]:
new_df['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'StephenLang',
 'MichelleRodriguez',
 'JamesCameron']

In [51]:
text1 = "Hey Buddy!!, How are you doing!?"

In [52]:
"".join(text1)

'Hey Buddy!!, How are you doing!?'

In [53]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [54]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez JamesCameron'

In [55]:
from gensim.models import Word2Vec
from sklearn.feature_extraction.text import CountVectorizer

### WORD2VEC

In [56]:
# tags data
data = new_df['tags']

# Tokenize the text
tokenized_data = [text.split() for text in data]

# Train a Word2Vec model
word2vec_model = Word2Vec(sentences=tokenized_data, vector_size=100, window=5, min_count=1, workers=4)

# Function to get the average word vector for a document
def get_average_word_vector(words, model, num_features):
    feature_vector = np.zeros((num_features,), dtype="float32")
    num_words = 0
    index2word_set = set(model.wv.index_to_key)

    for word in words:
        if word in index2word_set:
            num_words += 1
            feature_vector = np.add(feature_vector, model.wv[word])

    if num_words != 0:
        feature_vector = np.divide(feature_vector, num_words)

    return feature_vector

# Get word vectors for each document
word_vectors = [get_average_word_vector(words, word2vec_model, 100) for words in tokenized_data]

# Convert word vectors to a numpy array
word_vectors_matrix = np.array(word_vectors)

In [57]:
word_vectors_matrix

array([[-0.0494832 ,  0.50351477, -0.04810208, ..., -0.05860919,
         0.31615216, -0.04069099],
       [-0.03915702,  0.62376565, -0.10370802, ..., -0.16435333,
         0.33971724, -0.04761235],
       [-0.06062172,  0.5709349 , -0.05591894, ..., -0.11807235,
         0.34155005, -0.03762876],
       ...,
       [-0.07060422,  0.6465537 , -0.06445697, ..., -0.21356912,
         0.31713873, -0.02901936],
       [-0.08986849,  0.725474  , -0.02410307, ..., -0.3651711 ,
         0.27994677,  0.0196895 ],
       [-0.06482136,  0.59509116, -0.0287041 , ..., -0.27570915,
         0.2411155 ,  0.00809949]], dtype=float32)

In [58]:
word_vectors_matrix.shape

(4806, 100)

### Calculating similarity matrix

In [59]:
from sklearn.metrics.pairwise import cosine_similarity

In [60]:
similarity = cosine_similarity(word_vectors_matrix)

In [61]:
similarity[0]

array([0.9999999 , 0.991453  , 0.9970137 , ..., 0.98483056, 0.9650505 ,
       0.97370255], dtype=float32)

In [62]:
new_df[new_df['title'] == 'The Dark Knight Rises'].index[0]

3

In [63]:
distances = sorted(list(enumerate(similarity[0])),reverse=True,key = lambda x: x[1])

In [64]:
distances

[(0, 0.9999999),
 (94, 0.99995077),
 (1036, 0.9998882),
 (941, 0.99988294),
 (1044, 0.99988276),
 (2014, 0.9998811),
 (104, 0.999863),
 (3760, 0.99985427),
 (3818, 0.99984896),
 (4039, 0.99984473),
 (826, 0.999827),
 (61, 0.99980885),
 (1602, 0.99980676),
 (4304, 0.9998037),
 (2394, 0.99979514),
 (378, 0.9997908),
 (151, 0.99978757),
 (3780, 0.9997874),
 (2888, 0.999775),
 (519, 0.9997746),
 (99, 0.99977124),
 (305, 0.99975127),
 (2699, 0.9997481),
 (511, 0.99974644),
 (4126, 0.9997427),
 (2945, 0.9997366),
 (977, 0.9997356),
 (1658, 0.99972934),
 (2448, 0.99972063),
 (807, 0.99971455),
 (1294, 0.99971294),
 (2847, 0.9997017),
 (4079, 0.99969953),
 (912, 0.99969286),
 (2381, 0.999691),
 (3840, 0.999684),
 (390, 0.9996772),
 (410, 0.9996713),
 (4365, 0.99966604),
 (176, 0.99966156),
 (3603, 0.9996615),
 (2155, 0.9996545),
 (1367, 0.9996532),
 (2202, 0.9996497),
 (322, 0.9996488),
 (2683, 0.99964803),
 (1197, 0.9996416),
 (2355, 0.99962234),
 (349, 0.99962115),
 (1364, 0.99962115),
 (2593, 0.99962074),
 (2020, 0.9996113),
 (1005, 0.99960977),
 (12, 0.99960816),
 (986, 0.9996072),
 (3261, 0.9996047),
 (1365, 0.99959844),
 (2801, 0.9995971),
 (3086, 0.9995888),
 (604, 0.9995791),
 (558, 0.99957496),
 (4463, 0.9995735),
 (2271, 0.99956876),
 (3709, 0.9995669),
 (1624, 0.9995584),
 (3352, 0.999558),
 (1527, 0.9995575),
 (1796, 0.9995482),
 (624, 0.9995467),
 (2855, 0.9995451),
 (2814, 0.9995309),
 (4540, 0.9995303),
 (1246, 0.99952453),
 (3572, 0.9995231),
 (3607, 0.9995174),
 (3354, 0.99951714),
 (1657, 0.99951667),
 (2241, 0.99951476),
 (1575, 0.99951404),
 (2162, 0.9995121),
 (684, 0.9995119),
 (64, 0.99951035),
 (1501, 0.99950725),
 (33, 0.9995065),
 (26, 0.9995054),
 (2279, 0.9995045),
 (2987, 0.99950325),
 (1010, 0.9995),
 (1939, 0.99949664),
 (621, 0.9994919),
 (2210, 0.9994855),
 (3039, 0.9994847),
 (1476, 0.9994812),
 (3347, 0.9994742),
 (3194, 0.9994732),
 (2415, 0.999473),
 (1577, 0.99947286),
 (3896, 0.999468),
 (2383, 0.99946624),
 (767, 0.9994649),
 (396, 0.9994616),
 (739, 0.99946046),
 (1334, 0.99946004),
 (1380, 0.9994517),
 (275, 0.99944943),
 (1754, 0.9994487),
 (3552, 0.99944574),
 (148, 0.9994457),
 (3049, 0.9994454),
 (1065, 0.9994446),
 (4615, 0.99944055),
 (3683, 0.99943954),
 (3918, 0.99943924),
 (4473, 0.9994347),
 (615, 0.9994268),
 (2807, 0.999424),
 (1562, 0.9994226),
 (3220, 0.99941486),
 (906, 0.99941254),
 (3072, 0.9994118),
 (1490, 0.9994093),
 (1373, 0.99940777),
 (884, 0.9994025),
 (88, 0.99939877),
 (899, 0.9993976),
 (564, 0.9993961),
 (1286, 0.9993944),
 (367, 0.99939156),
 (3893, 0.9993891),
 (1201, 0.9993859),
 (4368, 0.99938035),
 (711, 0.9993748),
 (813, 0.99937475),
 (2117, 0.9993723),
 (1880, 0.99936974),
 (31, 0.9993671),
 (3021, 0.9993602),
 (2445, 0.9993555),
 (1147, 0.99935424),
 (3374, 0.99934345),
 (3678, 0.9993336),
 (2633, 0.9993299),
 (1090, 0.99932677),
 (2206, 0.9993212),
 (683, 0.99931717),
 (2090, 0.99931514),
 (2455, 0.9993109),
 (1984, 0.9993105),
 (1589, 0.9993025),
 (1901, 0.9992966),
 (3413, 0.9992935),
 (44, 0.9992924),
 (4479, 0.9992915),
 (3391, 0.99928784),
 (152, 0.999286),
 (1922, 0.999286),
 (971, 0.9992769),
 (935, 0.99927646),
 (4085, 0.99926996),
 (1655, 0.9992648),
 (314, 0.9992622),
 (1400, 0.9992551),
 (54, 0.9992529),
 (1632, 0.99924505),
 (2861, 0.99924123),
 (3077, 0.99924093),
 (3996, 0.99923897),
 (1964, 0.9992378),
 (3136, 0.99923396),
 (2304, 0.9992327),
 (356, 0.9992312),
 (892, 0.99923),
 (1694, 0.999229),
 (980, 0.9992255),
 (1055, 0.99922526),
 (850, 0.999225),
 (2546, 0.99922436),
 (1672, 0.9992231),
 (2783, 0.999223),
 (4195, 0.99921113),
 (3625, 0.9992103),
 (95, 0.99919736),
 (4551, 0.9991951),
 (1108, 0.99919343),
 (1353, 0.9991911),
 (553, 0.99919003),
 (2890, 0.99917585),
 (744, 0.99917525),
 (2646, 0.9991748),
 (1618, 0.9991737),
 (2163, 0.999171),
 (1757, 0.9991703),
 (968, 0.99916786),
 (840, 0.9991671),
 (209, 0.99916553),
 (2564, 0.99915737),
 (1935, 0.99915045),
 (333, 0.999147),
 (2795, 0.9991433),
 (2914, 0.99914134),
 (606, 0.99914086),
 (4285, 0.99913955),
 (3834, 0.99913627),
 (2456, 0.99913335),
 (1707, 0.99912786),
 (778, 0.9991255),
 (278, 0.9991252),
 (3185, 0.9991155),
 (4030, 0.99911314),
 (3471, 0.9991085),
 (1448, 0.99910134),
 (1091, 0.9991004),
 (3094, 0.99909997),
 (506, 0.9990928),
 (4025, 0.9990829),
 (4635, 0.9990826),
 (1787, 0.999082),
 (945, 0.99906975),
 (2590, 0.9990616),
 (598, 0.9990577),
 (3537, 0.999052),
 (3234, 0.99905086),
 (2638, 0.99904704),
 (2724, 0.99904364),
 (4300, 0.99904156),
 (1613, 0.99904084),
 (1071, 0.9990363),
 (4591, 0.9990351),
 (3240, 0.9990335),
 (1437, 0.99903333),
 (4132, 0.999031),
 (1028, 0.9990291),
 (179, 0.99902755),
 (2737, 0.99902356),
 (1506, 0.99902254),
 (4081, 0.9990209),
 (2579, 0.9990191),
 (1414, 0.9990151),
 (2466, 0.9990137),
 (3832, 0.99899477),
 (3288, 0.9989899),
 (3774, 0.9989894),
 (880, 0.998989),
 (3367, 0.9989871),
 (1298, 0.9989836),
 (3911, 0.99898106),
 (1474, 0.9989779),
 (452, 0.9989757),
 (2342, 0.9989716),
 (1159, 0.9989714),
 (2077, 0.9989642),
 (4460, 0.99895924),
 (417, 0.9989587),
 (3550, 0.9989566),
 (1529, 0.998956),
 (3275, 0.99895376),
 (783, 0.99894875),
 (4441, 0.9989413),
 (1579, 0.9989388),
 (446, 0.998938),
 (70, 0.99893683),
 (4515, 0.99893606),
 (660, 0.99892706),
 (141, 0.9989247),
 (3613, 0.9989235),
 (3614, 0.9989224),
 (4715, 0.99891907),
 (319, 0.9989174),
 (287, 0.99891657),
 (2205, 0.99890965),
 (1335, 0.99890447),
 (2615, 0.9989011),
 (1660, 0.9988974),
 (2100, 0.9988925),
 (1907, 0.99889034),
 (1409, 0.9988811),
 (1911, 0.998881),
 (2175, 0.99887556),
 (2562, 0.99887395),
 (2038, 0.99887365),
 (1228, 0.99887276),
 (3671, 0.99887264),
 (3946, 0.99886835),
 (4053, 0.9988666),
 (1434, 0.99884635),
 (159, 0.9988459),
 (3006, 0.9988444),
 (465, 0.9988319),
 (2956, 0.99883),
 (4550, 0.9988259),
 (2880, 0.9988243),
 (695, 0.9988182),
 (2778, 0.9988153),
 (983, 0.998811),
 (2865, 0.9988041),
 (4078, 0.9988027),
 (3770, 0.99880105),
 (4638, 0.998795),
 (2501, 0.9987943),
 (4331, 0.99879134),
 (4750, 0.99878514),
 (3281, 0.99878335),
 (1289, 0.9987797),
 (1109, 0.9987785),
 (546, 0.9987762),
 (1570, 0.9987753),
 (1027, 0.9987721),
 (2761, 0.9987719),
 (267, 0.9987684),
 (642, 0.9987596),
 (867, 0.99875826),
 (625, 0.9987533),
 (505, 0.9987532),
 (122, 0.9987522),
 (78, 0.99874884),
 (1392, 0.99874747),
 (1158, 0.9987437),
 (2483, 0.9987437),
 (3363, 0.9987426),
 (73, 0.99874234),
 (2840, 0.99873865),
 (1351, 0.9987334),
 (3769, 0.9987268),
 (858, 0.99872565),
 (1824, 0.99871314),
 (3483, 0.99869996),
 (4542, 0.99869466),
 (2706, 0.9986918),
 (1161, 0.99869055),
 (1075, 0.99868435),
 (464, 0.9986823),
 (539, 0.99867487),
 (112, 0.9986747),
 (442, 0.9986644),
 (4211, 0.9986601),
 (4097, 0.99865943),
 (2418, 0.9986594),
 (2463, 0.99865746),
 (2312, 0.99865615),
 (1253, 0.9986543),
 (3127, 0.9986525),
 (737, 0.9986436),
 (82, 0.99863595),
 (3964, 0.9986343),
 (3972, 0.99861777),
 (774, 0.9986169),
 (1944, 0.99861205),
 (232, 0.9985999),
 (3420, 0.9985934),
 (2144, 0.9985929),
 (3205, 0.9985927),
 (4278, 0.9985907),
 (3752, 0.9985894),
 (1853, 0.99858904),
 (2126, 0.998589),
 (1134, 0.9985862),
 (873, 0.99858487),
 (2634, 0.9985839),
 (1361, 0.99858195),
 (1778, 0.99858177),
 (791, 0.9985704),
 (528, 0.9985665),
 (1631, 0.9985605),
 (972, 0.99856025),
 (1431, 0.99855894),
 (4062, 0.9985574),
 (121, 0.99855363),
 (72, 0.9985514),
 (3182, 0.99854845),
 (590, 0.9985423),
 (773, 0.9985393),
 (4333, 0.9985331),
 (4802, 0.99852395),
 (2809, 0.9985237),
 (1137, 0.99851507),
 (3336, 0.99851304),
 (3055, 0.9985127),
 (2266, 0.9985116),
 (108, 0.9985034),
 (4000, 0.9985029),
 (370, 0.9984919),
 (1596, 0.99849075),
 (161, 0.99848384),
 (1153, 0.99847686),
 (3541, 0.9984764),
 (3002, 0.99847233),
 (2390, 0.9984714),
 (1076, 0.99846816),
 (276, 0.9984649),
 (3376, 0.99846137),
 (4557, 0.9984555),
 (1619, 0.998452),
 (4536, 0.99845076),
 (177, 0.998445),
 (3804, 0.9984365),
 (4650, 0.9984348),
 (2863, 0.998426),
 (2256, 0.99842423),
 (308, 0.998422),
 (3510, 0.99842054),
 (2616, 0.9984141),
 (298, 0.99841297),
 (1850, 0.99840873),
 (4072, 0.9984056),
 (1226, 0.99839616),
 (771, 0.9983926),
 (157, 0.99839216),
 (4230, 0.99839205),
 (1280, 0.9983886),
 (3933, 0.99838805),
 (3430, 0.9983845),
 (3712, 0.99838096),
 (787, 0.9983795),
 (1299, 0.9983786),
 (1833, 0.9983765),
 (1518, 0.99837625),
 (2939, 0.9983718),
 (348, 0.998365),
 (4643, 0.998363),
 (3644, 0.99836296),
 (973, 0.9983623),
 (4571, 0.998358),
 (4777, 0.99835604),
 (2074, 0.99835384),
 (3786, 0.99834585),
 (891, 0.9983456),
 (1566, 0.9983443),
 (1142, 0.99834317),
 (4757, 0.99833554),
 (439, 0.99832886),
 (2334, 0.9983265),
 (3167, 0.9983156),
 (2416, 0.9983123),
 (2399, 0.9983084),
 (4718, 0.99830717),
 (2061, 0.99830264),
 (1079, 0.99830043),
 (2017, 0.99830025),
 (3124, 0.9982995),
 (3751, 0.99829876),
 (3923, 0.9982951),
 (653, 0.99829257),
 (1455, 0.9982905),
 (1199, 0.998288),
 (920, 0.9982843),
 (1539, 0.99828184),
 (4738, 0.9982675),
 (186, 0.9982626),
 (1805, 0.9982595),
 (3875, 0.99825525),
 (1052, 0.9982513),
 (2877, 0.99824935),
 (1316, 0.9982472),
 (489, 0.9982451),
 (3184, 0.9982433),
 (5, 0.9982432),
 (2129, 0.9982405),
 (2204, 0.99823993),
 (2374, 0.998234),
 (763, 0.9982335),
 (2255, 0.9982292),
 (2194, 0.9982278),
 (4020, 0.9982246),
 (2645, 0.9982227),
 (2618, 0.99821836),
 (165, 0.99821126),
 (3492, 0.9982104),
 (123, 0.99820846),
 (459, 0.99820155),
 (2698, 0.9981971),
 (1021, 0.9981963),
 (866, 0.998175),
 (2747, 0.99817294),
 (613, 0.99817234),
 (2660, 0.9981595),
 (2574, 0.9981507),
 (754, 0.99814534),
 (2313, 0.9981439),
 (1769, 0.9981426),
 (714, 0.9981421),
 (3301, 0.99814194),
 (3989, 0.99813694),
 (3745, 0.9981316),
 (2585, 0.9981266),
 (1524, 0.9981223),
 (2151, 0.99812186),
 (49, 0.9981213),
 (245, 0.99812114),
 (3627, 0.9981181),
 (203, 0.9981177),
 (1193, 0.998117),
 (3643, 0.99811155),
 (3656, 0.9981108),
 (3262, 0.9981099),
 (756, 0.9981082),
 (628, 0.998105),
 (354, 0.9980974),
 (1382, 0.9980971),
 (3087, 0.99809384),
 (3447, 0.99808943),
 (3496, 0.9980875),
 (4791, 0.99808365),
 (1879, 0.9980785),
 (3571, 0.99807507),
 (4704, 0.998071),
 (4130, 0.998059),
 (2284, 0.9980539),
 (4173, 0.9980452),
 (1285, 0.99804443),
 (1408, 0.9980223),
 (3598, 0.9980206),
 (2028, 0.9980084),
 (4645, 0.9980038),
 (233, 0.9979964),
 (1495, 0.99798846),
 (236, 0.9979851),
 (1105, 0.9979749),
 (2323, 0.9979722),
 (196, 0.997969),
 (2977, 0.9979554),
 (243, 0.99795187),
 (1133, 0.997947),
 (283, 0.9979463),
 (1830, 0.99794245),
 (3706, 0.9979424),
 (4444, 0.99793845),
 (2691, 0.99793655),
 (4412, 0.9979347),
 (4486, 0.9979265),
 (3242, 0.99792343),
 (2551, 0.99791014),
 (1667, 0.9978963),
 (2218, 0.9978958),
 (1662, 0.9978867),
 (931, 0.9978823),
 (244, 0.9978744),
 (808, 0.9978685),
 (3885, 0.9978411),
 (3579, 0.99783677),
 (2586, 0.9978356),
 (1882, 0.99783295),
 (2196, 0.99782103),
 (3202, 0.9978097),
 (3350, 0.9978085),
 (4172, 0.9978052),
 (2530, 0.9978023),
 (742, 0.99778795),
 (3506, 0.99777424),
 (1544, 0.9977727),
 (1971, 0.99775636),
 (1737, 0.9977561),
 (2060, 0.9977555),
 (1336, 0.9977535),
 (381, 0.9977373),
 (2386, 0.99773586),
 (268, 0.9977356),
 (263, 0.9977303),
 (1042, 0.9977282),
 (3529, 0.9977262),
 (3319, 0.99772537),
 (2249, 0.99772143),
 (105, 0.9977193),
 (3916, 0.9977184),
 (1260, 0.99771243),
 (2036, 0.99770856),
 (1776, 0.9977085),
 (2772, 0.9976919),
 (2858, 0.99768656),
 (690, 0.997683),
 (2786, 0.9976779),
 (2674, 0.9976758),
 (4026, 0.9976572),
 (2172, 0.99765575),
 (834, 0.99764645),
 (3600, 0.9976437),
 (1272, 0.9976409),
 (1029, 0.99763566),
 (416, 0.99763554),
 (3396, 0.997633),
 (1388, 0.99763274),
 (4395, 0.9976284),
 (2836, 0.9976237),
 (4568, 0.9976185),
 (2007, 0.9976013),
 (215, 0.9975973),
 (991, 0.99759245),
 (4375, 0.9975875),
 (1843, 0.9975701),
 (2331, 0.9975655),
 (814, 0.99755514),
 (4606, 0.99755424),
 (2352, 0.9975493),
 (449, 0.9975464),
 (2042, 0.9975446),
 (208, 0.9975438),
 (3069, 0.9975424),
 (2696, 0.9975411),
 (3147, 0.99754006),
 (800, 0.99753493),
 (4091, 0.99752754),
 (1275, 0.9975259),
 (134, 0.99750996),
 (16, 0.99749523),
 (3728, 0.9974937),
 (3338, 0.99749035),
 (3236, 0.9974847),
 (3994, 0.99746555),
 (1804, 0.9974631),
 (3749, 0.9974545),
 (2513, 0.99744904),
 (3943, 0.9974395),
 (2338, 0.99743724),
 (1073, 0.9974345),
 (3426, 0.99742734),
 (524, 0.9974256),
 (201, 0.9974252),
 (4499, 0.9974173),
 (2410, 0.9974149),
 (2520, 0.9974071),
 (2127, 0.9973983),
 (3665, 0.9973937),
 (1823, 0.99739033),
 (3845, 0.9973814),
 (3985, 0.9973788),
 (180, 0.99737656),
 (2999, 0.99737537),
 (1665, 0.99736416),
 (408, 0.99736357),
 (1745, 0.99735725),
 (1139, 0.99735636),
 (801, 0.99734944),
 (917, 0.9973494),
 (1064, 0.99734485),
 (194, 0.9973412),
 (618, 0.9973407),
 (3359, 0.99733377),
 (2066, 0.9973332),
 (2222, 0.9973316),
 (3155, 0.99732995),
 (1950, 0.99732906),
 (4654, 0.997329),
 (3079, 0.9973267),
 (1321, 0.9973259),
 (1458, 0.9973201),
 (164, 0.9973195),
 (1416, 0.997307),
 (1499, 0.99729854),
 (2518, 0.99728566),
 (455, 0.9972851),
 (2797, 0.9972798),
 (2078, 0.9972772),
 (40, 0.9972765),
 (1716, 0.9972765),
 (1156, 0.9972753),
 (295, 0.9972741),
 (4502, 0.9972507),
 (256, 0.9972379),
 (3023, 0.9972363),
 (34, 0.9972356),
 (1779, 0.997234),
 (2053, 0.9972337),
 (1466, 0.9972327),
 (297, 0.9972326),
 (3988, 0.99723184),
 (490, 0.99719596),
 (1207, 0.99719286),
 (2751, 0.9971918),
 (1884, 0.99718744),
 (2425, 0.99718726),
 (3068, 0.9971852),
 (210, 0.9971653),
 (1001, 0.997163),
 (3516, 0.99716234),
 (2095, 0.9971594),
 (433, 0.99715734),
 (3280, 0.99715465),
 (2675, 0.99715453),
 (2727, 0.9971497),
 (1004, 0.9971468),
 (117, 0.99714524),
 (2780, 0.9971445),
 (2461, 0.99714446),
 (3173, 0.9971361),
 (510, 0.9971288),
 (4083, 0.9971282),
 (4457, 0.9971262),
 (4202, 0.9971251),
 (1511, 0.997125),
 (119, 0.9971216),
 (2764, 0.9971183),
 (1802, 0.9971182),
 (4253, 0.9971157),
 (4673, 0.9971055),
 (2413, 0.997097),
 (1713, 0.9970945),
 (168, 0.99709034),
 (76, 0.9970885),
 (823, 0.99707294),
 (527, 0.9970605),
 (2762, 0.99705744),
 (1194, 0.99705714),
 (218, 0.99705565),
 (1734, 0.99704754),
 (4189, 0.99704176),
 (260, 0.99704033),
 (607, 0.99703246),
 (1674, 0.9970294),
 (3157, 0.9970273),
 (1195, 0.9970262),
 (213, 0.9970228),
 (1488, 0.99702066),
 (2, 0.9970137),
 (3250, 0.9970121),
 (259, 0.99701035),
 (1721, 0.9970065),
 (2242, 0.9969898),
 (362, 0.99698603),
 (1030, 0.9969851),
 (3384, 0.996978),
 (139, 0.99697644),
 (487, 0.99697214),
 (2516, 0.9969565),
 (1860, 0.9969494),
 (3919, 0.99694765),
 (3130, 0.99694556),
 (4566, 0.99693894),
 (4234, 0.9969343),
 (3398, 0.99692833),
 (4293, 0.9969252),
 (4041, 0.99692404),
 (720, 0.9969177),
 (2521, 0.9969153),
 (3082, 0.99690926),
 (3511, 0.996904),
 (4623, 0.9969036),
 (1698, 0.99689126),
 (637, 0.99688977),
 (3403, 0.99688894),
 (2680, 0.99688745),
 (2824, 0.99688655),
 (571, 0.996886),
 (634, 0.9968854),
 (2051, 0.99688303),
 (1756, 0.9968823),
 (997, 0.9968816),
 (2075, 0.9968685),
 (1435, 0.99685806),
 (2339, 0.9968498),
 (3723, 0.9968496),
 (1443, 0.99683905),
 (1410, 0.9968366),
 (2073, 0.9968256),
 (2901, 0.99682385),
 (261, 0.99681723),
 (3443, 0.99681646),
 (1438, 0.99681014),
 (3356, 0.9968077),
 (1083, 0.99680763),
 (3756, 0.99680513),
 (1670, 0.99680316),
 (3702, 0.99680144),
 (1078, 0.9967882),
 (2161, 0.996787),
 (3725, 0.9967852),
 (418, 0.99676794),
 (608, 0.9967527),
 (413, 0.99674505),
 (4737, 0.99674505),
 (421, 0.99673975),
 (46, 0.99673563),
 (1502, 0.99673367),
 (1308, 0.9967303),
 (249, 0.99672383),
 (358, 0.99672335),
 (3534, 0.99670905),
 (876, 0.996703),
 (1097, 0.9966976),
 (3819, 0.99669355),
 (2584, 0.9966925),
 (4727, 0.99669164),
 (3479, 0.99668735),
 (1208, 0.9966867),
 (976, 0.99668115),
 (1601, 0.99667716),
 (570, 0.9966764),
 (937, 0.9966752),
 (185, 0.9966743),
 (3276, 0.99667203),
 (2353, 0.9966606),
 (1403, 0.9966572),
 (818, 0.9966557),
 (1573, 0.9966527),
 (1385, 0.9966453),
 (1170, 0.9966385),
 (2299, 0.9966361),
 (3243, 0.9966255),
 (169, 0.99661094),
 (1469, 0.9966103),
 (4548, 0.996605),
 (198, 0.9966021),
 (2672, 0.99660015),
 (1719, 0.99659926),
 (1183, 0.9965985),
 (2568, 0.99659723),
 (627, 0.996597),
 (1806, 0.99659556),
 (3427, 0.9965902),
 (2856, 0.99658406),
 (3868, 0.996579),
 (248, 0.996568),
 (995, 0.9965575),
 (2808, 0.99655485),
 (3879, 0.9965515),
 (2330, 0.9965472),
 (1923, 0.99654615),
 (195, 0.99653924),
 (1920, 0.9965256),
 (665, 0.9965076),
 (673, 0.996502),
 (3351, 0.9964986),
 (1069, 0.99648535),
 (3395, 0.9964755),
 (404, 0.9964672),
 (573, 0.9964629),
 (3060, 0.9964624),
 (2169, 0.9964545),
 (2868, 0.99644995),
 (1057, 0.99644256),
 (3663, 0.9964353),
 (2970, 0.9964337),
 (1080, 0.9964269),
 (3497, 0.9964188),
 (1750, 0.9964098),
 (2244, 0.9964086),
 (2240, 0.9963947),
 (2515, 0.9963945),
 (2601, 0.99638647),
 (4468, 0.9963851),
 (2139, 0.99638313),
 (3987, 0.99637806),
 (3741, 0.9963751),
 (748, 0.9963698),
 (3268, 0.99636483),
 (696, 0.9963606),
 (784, 0.9963501),
 (2741, 0.99634707),
 (2544, 0.99634105),
 (1032, 0.99634045),
 (1606, 0.9963364),
 (2326, 0.99633163),
 (1669, 0.99631536),
 (3432, 0.9963051),
 (2919, 0.9962992),
 (3449, 0.99629885),
 (2223, 0.9962919),
 (1016, 0.99629086),
 (2528, 0.99629015),
 (1062, 0.99628854),
 (4394, 0.9962809),
 (4561, 0.9962749),
 (3110, 0.99627477),
 (2120, 0.9962657),
 (2069, 0.9962592),
 (3241, 0.9962544),
 (2870, 0.99625427),
 (2833, 0.9962349),
 (1681, 0.9962261),
 (2886, 0.99622285),
 (3293, 0.9962139),
 (3160, 0.9962055),
 (2321, 0.99620205),
 (2377, 0.9962007),
 (2281, 0.99620026),
 (4324, 0.99619776),
 (1481, 0.99619174),
 (189, 0.99619097),
 (3128, 0.99618775),
 (3539, 0.9961824),
 (300, 0.9961816),
 (4470, 0.9961719),
 (1060, 0.9961713),
 (4517, 0.996164),
 (4637, 0.99616116),
 (4216, 0.9961569),
 (928, 0.9961513),
 (2964, 0.99615127),
 (562, 0.9961426),
 (844, 0.99614054),
 (638, 0.9961402),
 (2690, 0.9961398),
 (1068, 0.99613947),
 (2310, 0.99613917),
 (3141, 0.99613875),
 (2896, 0.99612707),
 (3159, 0.99612427),
 (172, 0.9961185),
 (2354, 0.99611753),
 (761, 0.9961148),
 (2955, 0.99611366),
 (4769, 0.99611306),
 (2600, 0.9961032),
 (2702, 0.9961027),
 (2871, 0.996099),
 (3778, 0.996087),
 (520, 0.996086),
 (2550, 0.99607724),
 (3428, 0.99605334),
 (8, 0.9960422),
 (3378, 0.99604136),
 (1774, 0.9960363),
 (2883, 0.99603343),
 (1690, 0.9960302),
 (2787, 0.9960192),
 (725, 0.9960184),
 (3530, 0.9960166),
 (3792, 0.9960147),
 (1676, 0.99601024),
 (1132, 0.9960095),
 (4456, 0.9960012),
 (1492, 0.99599624),
 (4104, 0.9959879),
 (2122, 0.99598616),
 (872, 0.99598),
 (4343, 0.9959792),
 (1569, 0.995966),
 (2482, 0.9959638),
 (4341, 0.995961),
 (4400, 0.9959594),
 (4134, 0.99595636),
 (2620, 0.99593496),
 (330, 0.99592686),
 (3001, 0.99592644),
 (1517, 0.9959167),
 (2094, 0.99591136),
 (191, 0.9959087),
 (3615, 0.99589366),
 (1236, 0.9958919),
 (2591, 0.9958768),
 (3775, 0.99587286),
 (3025, 0.99587274),
 (1746, 0.9958651),
 (1484, 0.99586433),
 (3320, 0.99585766),
 (3437, 0.9958551),
 (1835, 0.99585223),
 (2058, 0.99583244),
 (1224, 0.9958294),
 (3393, 0.99582916),
 (435, 0.9958287),
 (647, 0.99582785),
 (4736, 0.9958232),
 (2084, 0.99581593),
 (1726, 0.99580026),
 (3716, 0.99579334),
 (2873, 0.9957918),
 (2602, 0.9957884),
 (950, 0.9957867),
 (2404, 0.9957819),
 (1231, 0.9957775),
 (3340, 0.9957769),
 (1731, 0.9957686),
 (2444, 0.9957563),
 (3595, 0.99575436),
 (3773, 0.9957525),
 (111, 0.9957484),
 (43, 0.9957402),
 (3527, 0.9957347),
 (579, 0.995722),
 (538, 0.99571866),
 (2136, 0.99571687),
 (39, 0.99571425),
 (1666, 0.99571),
 (825, 0.995708),
 (2297, 0.9957049),
 (2093, 0.99569124),
 (4014, 0.9956899),
 (1616, 0.9956796),
 (2534, 0.9956793),
 (645, 0.99567056),
 (4185, 0.99565876),
 (1221, 0.9956564),
 (3264, 0.9956477),
 (3863, 0.99564296),
 (4052, 0.99563664),
 (1760, 0.9956317),
 (4575, 0.995624),
 (162, 0.9956198),
 (360, 0.99561006),
 (4248, 0.99560714),
 (3955, 0.9956038),
 (1012, 0.9955945),
 (3499, 0.99557275),
 (3282, 0.9955711),
 (2543, 0.9955627),
 (2718, 0.99555266),
 (1592, 0.99554986),
 (3010, 0.99553424),
 (2549, 0.99553174),

In [65]:
for i in distances[1:6]:
    print(new_df.iloc[i[0]].title)

Guardians of the Galaxy
Insomnia
13 Hours: The Secret Soldiers of Benghazi
Taken 2
In the Valley of Elah

In [66]:
#Helper function to recommend movie, by calculating similarity scores

def recommend_movie(movie):
    index = new_df[new_df['title'] == movie].index[0]                                         #Finding index of the input movie
    distances = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x: x[1])  #Calculating distances (similarity measure from that movie to each and every movie)
    print(f"These are the top 5 recommended movies based on your input '{movie}':")
    print("-" * 70)
    for i in distances[1:6]:                      #Looping only through next 5 distances in the array
        movie_title = new_df.iloc[i[0]].title     #Extracting the titles from new_df(dataframe)
        similarity_score = i[1]                   #Extracting similarity scores
        print(f"Movie: {movie_title}, Similarity Score: {similarity_score}")

In [67]:
recommend_movie('Be Cool')

These are the top 5 recommended movies based on your input 'Be Cool':
----------------------------------------------------------------------
Movie: Margin Call, Similarity Score: 0.9998770356178284
Movie: For Greater Glory - The True Story of Cristiada, Similarity Score: 0.9998762011528015
Movie: Elmer Gantry, Similarity Score: 0.9998114109039307
Movie: Blood Diamond, Similarity Score: 0.9998008012771606
Movie: San Andreas, Similarity Score: 0.9997990131378174

In [68]:
new_df.sample(3)

,movie_id,title,tags
3470,11191,Mystic Pizza,Three teenage girls come of age while working ...
2312,10065,The Amityville Horror,A family is terrorized by demonic forces after...
3229,152747,All Is Lost,"Deep into a solo voyage in the Indian Ocean, a..."

In [69]:
recommend_movie('Choke')

These are the top 5 recommended movies based on your input 'Choke':
----------------------------------------------------------------------
Movie: Drowning Mona, Similarity Score: 0.9998800754547119
Movie: Stardust, Similarity Score: 0.9998733401298523
Movie: Sinister, Similarity Score: 0.9998653531074524
Movie: Cop Land, Similarity Score: 0.9998592138290405
Movie: Ravenous, Similarity Score: 0.9998535513877869

In [70]:
recommend_movie("Pirates of the Caribbean: At World's End")

These are the top 5 recommended movies based on your input 'Pirates of the Caribbean: At World's End':
----------------------------------------------------------------------
Movie: Shrek 2, Similarity Score: 0.9999163150787354
Movie: Superman Returns, Similarity Score: 0.999907910823822
Movie: Shrek the Third, Similarity Score: 0.9999065399169922
Movie: Alvin and the Chipmunks: The Road Chip, Similarity Score: 0.9998741745948792
Movie: The Lion King, Similarity Score: 0.9998624324798584

### Cool!! This is working

In [71]:
import pickle

In [73]:
pickle.dump(new_df,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))